language: go

services:
  - elasticsearch

env:
  global:
    - ELASTIC_PORT: 9200
    - ELASTIC_URL: localhost

notifications:
  email: false

before_script:
  - sleep 10
  - go get github.com/golang/dep/... && go install github.com/golang/dep/...
  - go get github.com/DATA-DOG/godog/cmd/godog && go install github.com/DATA-DOG/godog/cmd/godog
  - go get gopkg.in/alecthomas/gometalinter.v1 && go install gopkg.in/alecthomas/gometalinter.v1 && gometalinter.v1 --install
  - dep ensure -vendor-only

script:
  - go install github.com/populin/popul.in/importer && importer data/geography/fixtures
  - go test -race -v
  - gometalinter.v1 --config gometalinter.json ./...
