version: '3.1'

services:

  populin-geography-api:
    build: 
      context: docker/golang
    container_name: populin-geography-api
    depends_on: 
      - populin-geography-elasticsearch
    environment: 
      POPULIN_GEOGRAPHY_ELASTIC_PORT: 9200
      POPULIN_GEOGRAPHY_ELASTIC_URL: populin-geography-elasticsearch
      POPULIN_GEOGRAPHY_API_ENV: dev
      POPULIN_GEOGRAPHY_API_PORT: 80
    networks:
      - geography
    ports:
      - 80:80
      - 6060:6060
    tty: true
    volumes: 
      - ".:/go/src/github.com/populin/popul.in"
    working_dir: /go/src/github.com/populin/popul.in

  populin-geography-elasticsearch:
    container_name: populin-geography-elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2"
    networks: 
      - geography
    ports: 
      - 9202:9200
    volumes: 
      - "./docker/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./data/elastic:/usr/share/elasticsearch/data"

  populin-geography-kibana:
    container_name: populin-geography-kibana
    depends_on: 
      - populin-geography-elasticsearch
    image: "docker.elastic.co/kibana/kibana-oss:6.2.2"
    networks: 
      - geography
    ports: 
      - 5601:5601
    volumes: 
      - "./docker/config/kibana.yml:/usr/share/kibana/config/kibana.yml"

networks:
  geography:
    driver: bridge